// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

// TODO: this import path needs to point to a runtime package that provides Spec and Register
import "github.com/swaggo/swag"

const docTemplateCustomDelims = `{
    "schemes": {% marshal .Schemes %},
    "swagger": "2.0",
    "info": {
        "description": "{%escape .Description%}",
        "title": "{%.Title%}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{%.Version%}"
    },
    "host": "{%.Host%}",
    "basePath": "{%.BasePath%}",
    "paths": {
        "/myfunc": {
            "get": {
                "description": "My Function",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.MyStruct"
                        }
                    }
                },
                "x-function": "MyFunc"
            }
        }
    },
    "definitions": {
        "api.MyStruct": {
            "type": "object",
            "properties": {
                "urltemplate": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfoCustomDelims holds exported Swagger Info so clients can modify it
var SwaggerInfoCustomDelims = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "Testing custom template delimeters",
	InfoInstanceName: "CustomDelims",
	SwaggerTemplate:  docTemplateCustomDelims,
	LeftDelim:        "{%",
	RightDelim:       "%}",
}

func init() {
	swag.Register(SwaggerInfoCustomDelims.InstanceName(), SwaggerInfoCustomDelims)
}
